
PORTNAME=	userns
PORTVERSION=	0.0.1
PORTREVISION=	4
CATEGORIES=	devel

MAINTAINER=	theron@FreeBSD.org
COMMENT=	Userspace tool to redirect filesystem access

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	therontarigo
GH_PROJECT=	freebsd-user-namespace
GH_TAGNAME=	4026b0cd39c7fb2d9fc220bd486dfb1231f9b8fa

MAKE_ARGS+=	MK_INSTALL_AS_USER=yes

.include <bsd.port.mk>
