
PORTNAME=	userns
PORTVERSION=	0.0.1
PORTREVISION=	5
CATEGORIES=	devel

MAINTAINER=	theron@FreeBSD.org
COMMENT=	Userspace tool to redirect filesystem access

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	therontarigo
GH_PROJECT=	freebsd-user-namespace
GH_TAGNAME=	eb14f633590c27dd6ee24423c38783b0d1237347

MAKE_ARGS+=	MK_INSTALL_AS_USER=yes

.include <bsd.port.mk>
