
PORTNAME=	userns
PORTVERSION=	0.0.1
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	theron@FreeBSD.org
COMMENT=	Userspace tool to redirect filesystem access

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	therontarigo
GH_PROJECT=	freebsd-user-namespace
GH_TAGNAME=	e4f123538d6a7f5f86cbe1fcb07c9f131d095767

.include <bsd.port.mk>
